# Generated by Django 4.2.16 on 2024-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
